services:
  - type: web
    name: apex-re-portal
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Apex RE Portal"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://apex-re-portal.onrender.com"
      - key: ASSET_URL
        value: "https://apex-re-portal.onrender.com"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
